name: Release Windows x64
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --global pkg
      - run: npm install --no-package-lock
      - run: npm run build-windows-x64
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: Installers/*.tpp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
